stages:
  - test

.conda_env_install: &conda_env_install
  before_script:
    - wget -nv -O ./miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash ./miniconda.sh -f -b -p ./miniconda
    - rm miniconda.sh
    - source miniconda/bin/activate
    - conda update conda
    - conda create -y -c bioconda -c conda-forge -n annotwg_env bcftools shellcheck
    - conda activate annotwg_env

tests:
  <<: *conda_env_install
  stage: test
  script:
    - export PATH="$PATH:$(readlink -f ./bin)"
    - shellcheck bin/* tests/*.sh
    - bash tests/tests.sh
